// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsxPT5PgOehwo35xOiVC3-TUfb4gxamEk',
    appId: '1:921273281062:web:3e3ac7970fedabbdca14e7',
    messagingSenderId: '921273281062',
    projectId: 'pateintrecord',
    authDomain: 'pateintrecord.firebaseapp.com',
    storageBucket: 'pateintrecord.appspot.com',
    measurementId: 'G-PNLQG910LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdgSkA5uiNRpTaLEIBXbBvaC9AqYKXLg',
    appId: '1:921273281062:android:0c8d36fe4ccca34bca14e7',
    messagingSenderId: '921273281062',
    projectId: 'pateintrecord',
    storageBucket: 'pateintrecord.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6vyWYl6xu5y5_P1HLNFbQ95JW3zXmYjU',
    appId: '1:921273281062:ios:1b83a6f142bfad8aca14e7',
    messagingSenderId: '921273281062',
    projectId: 'pateintrecord',
    storageBucket: 'pateintrecord.appspot.com',
    iosClientId: '921273281062-39tetd181eroo5g03dvgu2t6j4kpufv8.apps.googleusercontent.com',
    iosBundleId: 'com.patientrecord.app',
  );
}
